const admin = require('firebase-admin');
const config = require('./config');
const firebase = require('firebase');
// private key generated by firebase console...probably should not be on public github
const serviceAccount = require('./divieapp-firebase-adminsdk-574mb-3ee6b35d6c.json');

// initialize firebase!
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'https://divieapp.firebaseio.com'
});

firebase.initializeApp(config);

// initialize databse!
const db = admin.firestore();

// export both so other files can use it
module.exports = { admin, db };
